#!/usr/bin/env bash
#Installing nginx at web server web-01

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw 'Nginx HTTP'

sudo sh -C 'echo "Hello World!" > /var/www/html/index.html'
sudo nginx -t

sudo service nginx reload

